### PR TITLE
V0.7.25

### PR DESCRIPTION
**Pull request by SubatomicHero**
- ACL controls for emails

### CODE REVIEW

**Comment by enzor** [comment]
Are those changes specific for redding or generally for Alfresco?
Also: include tests! A good way to start can be by just checking the content of the haproxy.cfg configuration file using inspec. Here's an example.

https://github.com/Alfresco/chef-alfresco/blob/develop/test/integration/community-52/inspec/haproxy_spec.rb#L8

**Comment by SubatomicHero** [comment]
This is a PR from @amohammedalfresco , if you want some tests etc please speak to him

**Comment by enzor** [comment]
will do!

**Comment by enzor** [comment]
After talking with Abdul, according with him, i am rejecting this PR.
Reasoning: Those haproxy values are specific to our internal projects, and putting them here will making them default for *all* of our projects (internal and open source one).

**Pull request closed without merging**
